// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/8 14:36:13
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/hc/Desktop/code/toP/webClone/shindary_site/www.shindary.com/web_transfer/frontend_nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hc/Desktop/code/toP/webClone/shindary_site/www.shindary.com/web_transfer/frontend_nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hc/Desktop/code/toP/webClone/shindary_site/www.shindary.com/web_transfer/frontend_nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hc/Desktop/code/toP/webClone/shindary_site/www.shindary.com/web_transfer/frontend_nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hc/Desktop/code/toP/webClone/shindary_site/www.shindary.com/web_transfer/frontend_nuxt/plugins/**/*.{js,ts,mjs}","/Users/hc/Desktop/code/toP/webClone/shindary_site/www.shindary.com/web_transfer/frontend_nuxt/composables/**/*.{js,ts,mjs}","/Users/hc/Desktop/code/toP/webClone/shindary_site/www.shindary.com/web_transfer/frontend_nuxt/utils/**/*.{js,ts,mjs}","/Users/hc/Desktop/code/toP/webClone/shindary_site/www.shindary.com/web_transfer/frontend_nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/hc/Desktop/code/toP/webClone/shindary_site/www.shindary.com/web_transfer/frontend_nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/hc/Desktop/code/toP/webClone/shindary_site/www.shindary.com/web_transfer/frontend_nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/hc/Desktop/code/toP/webClone/shindary_site/www.shindary.com/web_transfer/frontend_nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;