
CREATE DATABASE IF NOT EXISTS shindary_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE shindary_db;

CREATE TABLE IF NOT EXISTS sites (
    id INT AUTO_INCREMENT PRIMARY KEY,
    site_code VARCHAR(50) UNIQUE,
    domain VARCHAR(255),
    name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    site_id INT,
    parent_id INT,
    name VARCHAR(255),
    name_en VARCHAR(255),
    name_es VARCHAR(255),
    slug VARCHAR(255),
    image_url VARCHAR(255),
    description TEXT,
    FOREIGN KEY (site_id) REFERENCES sites(id),
    FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    site_id INT,
    category_id INT,
    name VARCHAR(255),
    name_en VARCHAR(255),
    name_es VARCHAR(255),
    slug VARCHAR(255),
    description TEXT,
    part_number VARCHAR(100),
    oem_number VARCHAR(100),
    car_model VARCHAR(255),
    image_url VARCHAR(255),
    FOREIGN KEY (site_id) REFERENCES sites(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
);

-- Insert Default Site
INSERT IGNORE INTO sites (id, site_code, domain, name) VALUES (1, 'shindary', 'www.shindary.com', 'Shindary Auto Parts');

INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (1, 1, NULL, 'Selected Parts', 'selected-parts');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (2, 1, 1, 'Radiator', 'radiator');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (3, 1, 2, 'Part Number', 'part-number23');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (4, 1, 1, 'Stabillizer Connecting Rod / Control Arm/ Swing Arm', 'stabillizer-connecting-rod-control-arm-swing-arm');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (5, 1, 4, 'Stabillizer Connecting Rod', 'stabillizer-connecting-rod');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (6, 1, 4, 'Control Arm/ Swing Arm', 'control-arm-swing-arm');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (7, 1, 4, 'Ball Joint', 'ball-joint');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (8, 1, 1, 'Shock Absorber', 'shock-absorber');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (9, 1, 8, 'Part Number', 'part-number26');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (10, 1, 1, 'Brake Drum / Brake Disc', 'brake-drum-brake-disc');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (11, 1, 10, 'Brake Drum', 'brake-drum');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (12, 1, 10, 'Brake Disc', 'brake-disc');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (13, 1, 10, 'Part Number', 'part-number27');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (14, 1, 1, 'Clutch kit', 'clutch-kit');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (15, 1, 14, 'Part Number', 'part-number28');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (16, 1, NULL, 'Hot Models', 'hot-models');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (17, 1, 16, 'VW', 'vw');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (18, 1, 17, 'ID 4', 'id-4');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (19, 1, 17, 'JETTA VS5', 'jetta-vs5');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (20, 1, 16, 'TESLA', 'tesla');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (21, 1, 20, 'Model 3', 'model-3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (22, 1, 20, 'Model Y', 'model-y');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (23, 1, 16, 'GAC', 'gac');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (24, 1, 16, 'HOZON', 'hozon');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (25, 1, 24, 'NETA V', 'neta-v');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (26, 1, 16, 'CHANGAN/CHANA', 'changan-chana');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (27, 1, 26, 'EV460', 'ev460');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (28, 1, 26, 'EADO PLUS', 'eado-plus');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (29, 1, 26, 'UNI-K', 'uni-k');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (30, 1, 26, 'UNI-T', 'uni-t');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (31, 1, 26, 'UNI-V', 'uni-v');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (32, 1, 26, 'ALSVIN', 'alsvin');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (33, 1, 26, 'X7', 'x7-changan');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (34, 1, 26, 'GRAND VAN TURISMO', 'grand-van-turismo');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (35, 1, 26, 'E-star', 'e-star');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (36, 1, 26, 'CX70', 'cx70');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (37, 1, 26, 'CS15', 'cs15');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (38, 1, 26, 'CS35', 'cs35');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (39, 1, 26, 'CS75', 'cs75');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (40, 1, 26, 'CS85', 'cs85');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (41, 1, 26, 'CS95', 'cs95');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (42, 1, 26, 'EADO', 'eado');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (43, 1, 26, 'Star pickup-MD201', 'star-pickup-md201');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (44, 1, 26, 'Star pickup-MS201', 'star-pickup-ms201');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (45, 1, 26, 'M201', 'm201');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (46, 1, 26, 'Star 7', 'star-7');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (47, 1, 26, 'Star 9', 'star-9');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (48, 1, 26, 'SC1021', 'sc1021');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (49, 1, 26, 'SC1040', 'sc1040');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (50, 1, 26, 'SC1050', 'sc1050');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (51, 1, 26, 'SC6363', 'sc6363');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (52, 1, 26, 'SC6350', 'SC6350');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (53, 1, 26, 'BENNI', 'benni');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (54, 1, 26, 'Part Number', 'part-number-3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (55, 1, 16, 'CHEVROLET', 'chevrolet');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (56, 1, 55, 'Menlo EV', 'menlo-ev');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (57, 1, 55, 'Cavalier', 'cavalier');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (58, 1, 55, 'CAPTIVA', 'captiva');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (59, 1, 55, 'ONIX', 'onix');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (60, 1, 55, 'New Sail', 'new-sail');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (61, 1, 55, 'Sail 3', 'sail-3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (62, 1, 55, 'N200', 'n200');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (63, 1, 55, 'N300P', 'n300p');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (64, 1, 55, 'Sonic', 'sonic');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (65, 1, 55, 'Spark', 'spark');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (66, 1, 55, 'Cruze', 'cruze');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (67, 1, 55, 'Part Number', 'part-number-5');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (68, 1, 16, 'CHERY', 'chery');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (69, 1, 68, 'Arrizo 3', 'arrizo-3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (70, 1, 68, 'Tiggo 7 pro', 'tiggo-7-pro');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (71, 1, 68, 'JETOUR X70 PLUS', 'jetour-x70-plus');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (72, 1, 68, 'Arrizo 6', 'arrizo-6');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (73, 1, 68, 'OMODA C5', 'omoda-c5');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (74, 1, 68, 'JETOUR DASHING', 'jetour-dashing');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (75, 1, 68, 'TIGGO2 PRO', 'tiggo2-pro');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (76, 1, 68, 'Q22', 'q22');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (77, 1, 68, 'X Cross', 'x-cross');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (78, 1, 68, 'TIGGO8', 'tiggo8');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (79, 1, 68, 'A1', 'a1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (80, 1, 68, 'A3', 'a3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (81, 1, 68, 'QQ3', 'qq3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (82, 1, 68, 'New QQ', 'new-qq');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (83, 1, 68, 'TIGGO', 'tiggo');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (84, 1, 68, 'TIGGO2', 'tiggo2');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (85, 1, 68, 'TIGGO 4', 'tiggo-4');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (86, 1, 68, 'TIGGO5', 'tiggo5');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (87, 1, 68, 'Q22L', 'Q22L');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (88, 1, 68, 'Q22B', 'q22b');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (89, 1, 68, 'S22', 's22');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (90, 1, 68, 'S22L', 's22l');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (91, 1, 68, 'E5', 'e5');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (92, 1, 68, 'J15', 'j15');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (93, 1, 68, 'Part Number', 'part-number-7');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (94, 1, 16, 'HYUNDAI', 'hyundai');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (95, 1, 94, 'Part Number', 'part-number-15');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (96, 1, 94, 'Accent', 'accent');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (97, 1, 94, 'Tucson', 'tucson');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (98, 1, 94, 'Others', 'hyundai-others');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (99, 1, 16, 'LIFAN', 'lifan');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (100, 1, 99, 'Part Number', 'part-number-9');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (101, 1, 99, '320', '320');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (102, 1, 99, '330', '330');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (103, 1, 99, '520', '520');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (104, 1, 99, '530', '530');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (105, 1, 99, '620', '620');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (106, 1, 99, 'Solano 2-650', 'solano-2-650');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (107, 1, 99, '720', '720');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (108, 1, 99, '820', '820');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (109, 1, 99, 'X50', 'x50');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (110, 1, 99, 'X60', 'x60');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (111, 1, 99, 'LF1022', 'lf1022');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (112, 1, 99, 'LF6401', 'lf6401');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (113, 1, 99, 'LF6420', 'lf6420');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (114, 1, 16, 'KIA', 'kia');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (115, 1, 114, 'Part Number', 'part-number19');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (116, 1, 114, 'CERATO', 'cerato');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (117, 1, 114, 'Rio', 'rio');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (118, 1, 114, 'Others', 'kia-others');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (119, 1, 16, 'GREAT WALL', 'greatwall');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (120, 1, 119, 'HAVAl JOLION', 'haval-jolion');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (121, 1, 119, 'DARGO', 'dargo');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (122, 1, 119, 'TANK 300', 'tank-300');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (123, 1, 119, 'TANK 500', 'tank-500');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (124, 1, 119, 'F7', 'f7');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (125, 1, 119, 'C30', 'c30');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (126, 1, 119, 'M4', 'm4');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (127, 1, 119, 'H3', 'h3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (128, 1, 119, 'H5', 'h5');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (129, 1, 119, 'H5-E', 'h5-e');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (130, 1, 119, 'HAVAL H6', 'haval-h6');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (131, 1, 119, 'WINGLE', 'wingle');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (132, 1, 119, 'Part Number', 'part-number-2');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (133, 1, 16, 'FORD', 'ford');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (134, 1, 133, 'Part Number', 'part-number21');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (135, 1, 133, 'TERRITORY EV', 'territory-ev');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (136, 1, 133, 'TERRITORY', 'territory');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (137, 1, 133, 'Escape', 'escape');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (138, 1, 133, 'Ecosport', 'ecosport');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (139, 1, 133, 'Fiesta', 'fiesta');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (140, 1, 133, 'Edge', 'edge');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (141, 1, 133, 'Explorer Xlt', 'explorer-xlt');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (142, 1, 133, 'Fusion', 'fusion');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (143, 1, 133, 'Transit', 'transit');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (144, 1, 133, 'Ford-others', 'ford-others');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (145, 1, 16, 'ZOTYE', 'zotye');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (146, 1, 145, 'X7', 'x7');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (147, 1, 145, 'Z300', 'z300');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (148, 1, 145, 'T600', 't600');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (149, 1, 145, '2008', '2008');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (150, 1, 145, '5008', '5008');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (151, 1, 16, 'NISSAN', 'nissan');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (152, 1, 151, 'Sylphy EV', 'sylphy-ev');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (153, 1, 151, 'ZNA Cabstar NT400', 'zna-cabstar-nt400');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (154, 1, 151, 'Tiida', 'tiida');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (155, 1, 151, 'March', 'march');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (156, 1, 151, 'Cabstar', 'cabstar');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (157, 1, 151, 'D22', 'd22');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (158, 1, 151, 'E25', 'e25');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (159, 1, 151, 'Sunny', 'sunny');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (160, 1, 151, 'Qashqai', 'qashqai');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (161, 1, 151, 'Sylphy', 'sylphy');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (162, 1, 151, 'KICKS', 'kicks');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (163, 1, 151, 'SENTRA B17', 'sentra-b17');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (164, 1, 151, 'VERSA', 'versa');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (165, 1, 151, 'X-TRAIL', 'x-trail');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (166, 1, 151, 'Nissan-others', 'nissan-others');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (167, 1, 151, 'Part Number', 'part-number17');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (168, 1, 16, 'BRILLIANCE', 'brilliance');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (169, 1, 168, 'Part Number', 'part-number-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (170, 1, 168, 'H220', 'h220');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (171, 1, 168, 'H230', 'h230');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (172, 1, 168, 'H320', 'h320');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (173, 1, 168, 'H330', 'h330');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (174, 1, 16, 'TOYOTA', 'toyota');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (175, 1, 174, 'Part Number', 'part-number18');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (176, 1, 174, 'Bz4X Long Range Pro', 'bz4x-long-range-pro');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (177, 1, 174, 'HILUX', 'hilux');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (178, 1, 174, 'RAV', 'rav');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (179, 1, 174, 'Corolla', 'corolla');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (180, 1, 16, 'BYD', 'byd');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (181, 1, 180, 'D1', 'd1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (182, 1, 180, 'SEAL', 'seal');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (183, 1, 180, 'GULL', 'gull');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (184, 1, 180, 'SONG L', 'song-l');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (185, 1, 180, 'T3', 't3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (186, 1, 180, 'E2', 'e2');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (187, 1, 180, 'NEW E2', 'new-e2');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (188, 1, 180, 'E5', 'e5-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (189, 1, 180, 'E6', 'e6');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (190, 1, 180, 'HAN', 'han');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (191, 1, 180, 'QIN', 'qin');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (192, 1, 180, 'SONG', 'song');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (193, 1, 180, 'SONG PLUS', 'song-plus');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (194, 1, 180, 'TANG EV', 'tang-ev');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (195, 1, 180, 'ATTO3', 'atto3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (196, 1, 180, 'YUAN PRO', 'yuan-pro');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (197, 1, 180, 'F0', 'f0');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (198, 1, 180, 'F3', 'f3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (199, 1, 180, 'S6', 's6');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (200, 1, 180, 'L3', 'l3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (201, 1, 180, 'Part Number', 'part-number');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (202, 1, 16, 'SAIC', 'saic');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (203, 1, 202, 'MAXUS EV30', 'maxus-ev30');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (204, 1, 202, 'MG eHS', 'mg-ehs');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (205, 1, 202, 'MG Comet', 'mg-comet');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (206, 1, 202, 'MG ZX', 'mg-zx');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (207, 1, 202, 'MG3', 'mg3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (208, 1, 202, 'MG5', 'mg5');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (209, 1, 202, 'MG6', 'mg6');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (210, 1, 202, 'MG GT', 'mg-gt');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (211, 1, 202, 'MG GS', 'mg-gs');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (212, 1, 202, 'MG 350', 'mg-350');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (213, 1, 202, 'MG ZS', 'mg-zs');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (214, 1, 202, 'MAXUS-G10', 'maxus-g10');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (215, 1, 202, 'MAXUS T60-DIESEL', 'maxus-t60-diesel');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (216, 1, 202, 'MAXUS V80-DIESEL', 'maxus-v80-diesel');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (217, 1, 202, 'MG RX5', 'mg-rx5');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (218, 1, 202, 'Part Number', 'part-number-8');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (219, 1, 16, 'SUZUKI', 'suzuki');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (220, 1, 219, 'Part Number', 'part-number-50');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (221, 1, 219, 'SX4', 'sx4');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (222, 1, 16, 'DONGFENG', 'dongfeng');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (223, 1, 222, 'EC31', 'ec31');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (224, 1, 222, 'VOYAH FREE', 'voyah-free');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (225, 1, 222, 'JOYEAR X3', 'joyear-x3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (226, 1, 222, 'T5 EVO', 't5-evo');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (227, 1, 222, 'T5 L', 't5-l');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (228, 1, 222, 'DFM SHINE', 'dfm-shine');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (229, 1, 222, 'EC35', 'ec35');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (230, 1, 222, 'M5 EV', 'm5-ev');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (231, 1, 222, 'S60 EV', 's60-ev');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (232, 1, 222, 'AX4', 'ax4');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (233, 1, 222, 'SX6', 'sx6');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (234, 1, 222, 'K01', 'k01');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (235, 1, 222, 'K01S', 'dfsk');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (236, 1, 222, 'K02', 'k02');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (237, 1, 222, 'K07', 'k07');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (238, 1, 222, 'V21', 'v21');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (239, 1, 222, 'V22', 'v22');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (240, 1, 222, 'V27', 'v27');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (241, 1, 222, 'V29', 'v29');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (242, 1, 222, 'C37', 'c37');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (243, 1, 222, 'H30cross', 'h30cross');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (244, 1, 222, 'AX7', 'ax7');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (245, 1, 222, 'S50', 's50');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (246, 1, 222, 'SX5', 'sx5');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (247, 1, 222, 'Glory 330', 'glory-330');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (248, 1, 222, 'Glory 580', 'glory-580');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (249, 1, 222, 'RICH', 'rich');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (250, 1, 222, 'Part Number', 'part-number-13');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (251, 1, 16, 'HONDA', 'honda');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (252, 1, 251, 'M-NV', 'm-nv');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (253, 1, 251, 'ACCORD', 'accord');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (254, 1, 251, 'CIVIC', 'civic');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (255, 1, 251, 'CR-V', 'cr-v');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (256, 1, 16, 'JAC', 'jac');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (257, 1, 256, 'E10X', 'e10x');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (258, 1, 256, 'E-JS4', 'e-js4');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (259, 1, 256, 'J7', 'j7');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (260, 1, 256, 'EJ7', 'ej7');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (261, 1, 256, 'J2', 'j2');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (262, 1, 256, 'J3', 'j3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (263, 1, 256, 'J5', 'j5');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (264, 1, 256, 'S2', 's2');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (265, 1, 256, 'S3', 's3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (266, 1, 256, 'S5', 's5');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (267, 1, 256, 'MPV-diesel', 'mpv-diesel');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (268, 1, 256, 'MPV-gasoline', 'mpv-gasoline');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (269, 1, 256, 'SUNRAY', 'sunray');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (270, 1, 256, 'K250', 'k250');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (271, 1, 256, 'HFC1036', 'hfc1036');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (272, 1, 256, 'HFC1042', 'hfc1042');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (273, 1, 256, 'HFC1061', 'hfc1061');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (274, 1, 256, 'HFC1121', 'hfc1121');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (275, 1, 256, 'RENI', 'reni');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (276, 1, 256, 'Part Number', 'part-number-10');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (277, 1, 16, 'BAIC', 'baic');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (278, 1, 277, 'BJ40', 'bj40');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (279, 1, 277, 'X35', 'x35');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (280, 1, 277, 'C52X', 'c52x');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (281, 1, 277, 'T205D', 't205d');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (282, 1, 277, '205', '205%201');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (283, 1, 277, '206', '206%20%201');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (284, 1, 277, '206C', '206c');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (285, 1, 277, 'M20', 'm20%201');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (286, 1, 277, 'M30', 'm30%201');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (287, 1, 277, 'S2', 's2%201');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (288, 1, 277, 'S3', 's3%201');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (289, 1, 277, 'H2', 'h2%201');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (290, 1, 16, 'GEELY', 'geely');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (291, 1, 290, 'Coolray', 'coolray');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (292, 1, 290, 'GEOMETRY C', 'geometry-c');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (293, 1, 290, 'GEOMETRY E', 'geometry-e');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (294, 1, 290, 'EMGRAND', 'emgrand');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (295, 1, 290, 'GX3', 'gx3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (296, 1, 290, 'ZHIDOU D2S', 'zhidou-d2s');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (297, 1, 290, 'EC7', 'ec7');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (298, 1, 290, 'EC8', 'ec8');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (299, 1, 290, 'GC7', 'gc7');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (300, 1, 290, 'GX7', 'gx7');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (301, 1, 290, 'EX7', 'ex7');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (302, 1, 290, 'CK', 'CK');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (303, 1, 290, 'MK07', 'mk07');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (304, 1, 290, 'MK08', 'MK08');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (305, 1, 290, 'Part Number', 'part-number-11');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (306, 1, 16, 'FAW', 'faw');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (307, 1, 306, 'Part Number', 'part-number-4');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (308, 1, 306, 'V5', 'v5');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (309, 1, 306, 'V80', 'v80');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (310, 1, 306, 'R7', 'r7');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (311, 1, 306, 'B50', 'b50');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (312, 1, 306, 'B70', 'b70');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (313, 1, 306, 'X80', 'x80');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (314, 1, 16, 'JINBEI', 'jinbei');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (315, 1, 314, 'SY6482N3', 'sy6482n3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (316, 1, 314, 'SY6482Q3', 'sy6482q3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (317, 1, 16, 'WULING', 'wuling');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (318, 1, 317, 'MINIEV', 'miniev');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (319, 1, 317, 'ALVEZ', 'alvez');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (320, 1, 317, 'GP50', 'gp50');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (321, 1, 317, 'SC6367', 'sc6367');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (322, 1, 317, 'Part Number', 'part-number-6');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (323, 1, 16, 'FOTON', 'foton');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (324, 1, 323, 'Part Number', 'part-number-12');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (325, 1, 323, 'V1', 'v1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (326, 1, 323, 'AUMARK', 'aumark');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (327, 1, 323, 'VIEW C1', 'view-c1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (328, 1, 323, 'Gratour T3', 'gratour-t3');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (329, 1, 323, 'BJ1043', 'bj1043');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (330, 1, 323, 'BJ1039', 'bj1039');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (331, 1, 323, 'BJ1061', 'bj1061');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (332, 1, 323, 'BJ1049', 'bj1049');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (333, 1, 16, 'HAFEI', 'hafei');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (334, 1, 333, 'Part Number', 'part-number-41');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (335, 1, 333, 'MINYI', 'minyi');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (336, 1, 333, 'ZHONGYI', 'zhongyi');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (337, 1, 16, 'CHANGHE', 'changhe');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (338, 1, 337, 'M50S', 'm50s');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (339, 1, 337, 'Q35', 'q35');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (340, 1, 337, 'CH6390', 'ch6390');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (341, 1, 16, 'GONOW', 'gonow');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (342, 1, 341, 'TROY 500', 'troy-500');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (343, 1, 341, 'GA6380', 'ga6380');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (344, 1, 16, 'SHINERAY', 'shineray');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (345, 1, 344, 'X30L', 'x30l');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (346, 1, 344, 'T30', 't30');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (347, 1, NULL, 'Commercial', 'commercial');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (348, 1, 347, 'Engine', 'engine');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (349, 1, 348, 'Chaoyang Diesel', 'chaoyang-diesel');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (350, 1, 348, 'Yuchai', 'yuchai');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (351, 1, 348, 'Cummins', 'cummins');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (352, 1, 348, 'Yunnei', 'yunnei');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (353, 1, 347, 'Gearbox', 'gearbox-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (354, 1, 347, 'Axle', 'axle');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (355, 1, 347, 'CHANGAN', 'changan');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (356, 1, 355, 'Hunter', 'hunter-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (357, 1, 347, 'GREAT WALL', 'great-wall');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (358, 1, 357, 'Wingle 5', 'wingle-5-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (359, 1, 357, 'Wingle 7', 'wingle-7-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (360, 1, 357, 'POER', 'poer');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (361, 1, 347, 'ZNA', 'zna');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (362, 1, 361, 'RICH 6', 'rich-6');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (363, 1, 361, 'Spare parts', 'spare-parts-zna');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (364, 1, 347, 'FOTON', 'foton-2');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (365, 1, 364, 'AUMAN GTL', 'auman-gtl');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (366, 1, 364, 'OLLIN TX', 'ollin-tx');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (367, 1, 364, 'TUNLAND', 'tunland-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (368, 1, 364, 'AUMARK', 'aumark-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (369, 1, 364, 'TAONO', 'taono');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (370, 1, 364, 'Spare parts', 'spare-parts-foton');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (371, 1, 347, 'JAC', 'jac-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (372, 1, 371, 'T8', 't8');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (373, 1, 371, 'T6', 't6-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (374, 1, 371, 'D870', 'd870');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (375, 1, 371, 'Spare parts', 'spare-parts-jac');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (376, 1, 347, 'JMC', 'jmc-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (377, 1, 376, 'N800', 'n800');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (378, 1, 376, 'N700', 'n700');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (379, 1, 376, 'Spare parts', 'spare-parts-jmc');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (380, 1, 376, 'VIGUS', 'vigus');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (381, 1, 376, 'N720', 'n720');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (382, 1, 347, 'SINOTRUK', 'sinotruk-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (383, 1, 347, 'SHACMAN', 'shacman-2');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (384, 1, 347, 'MAXUS', 'maxus');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (385, 1, 384, 'C35', 'c35');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (386, 1, 384, 'T60', 't60');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (387, 1, 384, 'Spare parts', 'spare-parts-maxus');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (388, 1, 347, 'FAW', 'faw-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (389, 1, 388, ' Tiger VH', '-tiger-vh');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (390, 1, 388, 'J5M', 'j5m');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (391, 1, 388, 'J5P', 'j5p');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (392, 1, 388, 'JH6', 'jh6');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (393, 1, 388, 'GF3000', 'gf3000');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (394, 1, 388, 'Spare parts', 'spare-parts-faw');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (395, 1, 347, 'DFAC', 'dfac');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (396, 1, 395, 'DOLIKA', 'dolika');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (397, 1, 395, 'Captain C', 'captain-c');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (398, 1, 395, 'Captain N', 'captain-n');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (399, 1, 395, 'Spare parts', 'spare-parts-dfac');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (400, 1, 347, 'ISUZU', 'isuzu-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (401, 1, 400, 'D-MAX', 'd-max-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (402, 1, 347, 'ZX AUTO', 'zx-auto');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (403, 1, 347, 'KINGLONG', 'kinglong-1');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (404, 1, 347, 'ZHONGTONG BUS', 'zhongtong-bus');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (405, 1, 347, 'ANKAI BUS', 'ankai-bus');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (406, 1, 347, 'HIGER', 'higer');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (407, 1, 347, 'YUTONG', 'yutong-2');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (408, 1, NULL, 'Hot Selling', 'hot-selling');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (409, 1, NULL, 'System Components', 'system-components');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (410, 1, 409, 'Engine System', 'engine-system');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (411, 1, 410, 'Turbocharger', 'turbocharger');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (412, 1, 410, 'Short Engine', 'short-engine');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (413, 1, 409, 'Maintenance parts', 'maintenance-parts');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (414, 1, 413, 'Part Number', 'part-number35');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (415, 1, 413, 'Filters', 'filters');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (416, 1, 413, 'Bearings', 'bearings');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (417, 1, 409, 'Crankshaft Connecting Rod System', 'crankshaft-connecting-rod-system');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (418, 1, 417, 'Part Number', 'part-number31');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (419, 1, 417, 'Crankshaft Bearing & Connecting Rod Bearing', 'crankshaft-bearing-connecting-rod-bearing');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (420, 1, 417, 'Cylinder Liner', 'cylinder-liner');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (421, 1, 417, 'Piston', 'piston');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (422, 1, 417, 'Piston Ring', 'piston-ring');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (423, 1, 417, 'Crankshaft', 'crankshaft');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (424, 1, 417, 'Connecting Rod', 'connecting-rod');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (425, 1, 409, 'Intake and exhaust system', 'intake-and-exhaust-system');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (426, 1, 425, 'Valve', 'valve');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (427, 1, 425, 'Cylinder Head', 'cylinder-head');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (428, 1, 425, 'Camshaft', 'camshaft');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (429, 1, 425, 'Engine gasket repair Kit', 'engine-gasket-repair-kit');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (430, 1, 409, 'Timing system', 'timing-system');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (431, 1, 430, 'Part Number', 'part-number30');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (432, 1, 430, 'Belt', 'belt');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (433, 1, 430, 'Timing Chain', 'timing-chain');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (434, 1, 430, 'Tensioner', 'tensioner');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (435, 1, 430, 'Timing Repair Kit', 'timing-repair-kit');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (436, 1, 409, 'Ignition System', 'ignition-system');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (437, 1, 436, 'Part Number', 'part-number33');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (438, 1, 436, 'Spark Plug', 'spark-plug');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (439, 1, 436, 'Ignition Coil', 'ignition%20coil');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (440, 1, 436, 'Ignition Cable', 'ignition-cable');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (441, 1, 436, 'Generator', 'generator');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (442, 1, 436, 'Starter', 'starter');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (443, 1, 436, 'Throttle Valve', 'throttle-valve');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (444, 1, 409, 'Fuel injection', 'fuel-injection');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (445, 1, 444, 'Part Number', 'part-number34');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (446, 1, 444, 'Oxygen Sensor', 'oxygen-sensor');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (447, 1, 444, 'Fuel Pump', 'fuel-pump');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (448, 1, 444, 'Thermostat', 'thermostat');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (449, 1, 444, 'Sensors', 'sensors');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (450, 1, 444, 'Idle Motor', 'idle-motor');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (451, 1, 444, 'Fuel Injector', 'fuel%20injector');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (452, 1, 444, 'Fuel Injection Pump', 'fuel-injection-pump');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (453, 1, 409, 'Cooling System', 'cooling%20system');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (454, 1, 453, 'Fan', 'fan');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (455, 1, 453, 'Heater Core', 'heater-core');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (456, 1, 453, 'Water Pump', 'water%20pump');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (457, 1, 453, 'Oil Pump', 'oil%20pump');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (458, 1, 453, 'Compressor', 'compressor');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (459, 1, 453, 'Part Number', 'part-number29');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (460, 1, 453, 'Condenser', 'condenser');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (461, 1, 409, 'Clutch System', 'clutch-system');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (462, 1, 461, 'Clutch Master/Slave Cylinder', 'clutch-master-slave-cylinder');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (463, 1, 409, 'Transmission system', 'transmission-system');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (464, 1, 463, 'CV Joint Kit', 'cv-joint-kit');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (465, 1, 463, 'Main Reducer', 'main-reducer');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (466, 1, 463, 'Drive Shaft', 'drive-shaft');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (467, 1, 463, 'Cage Repair Kit', 'cage-repair-kit');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (468, 1, 463, 'Transmission shaft', 'transmission-shaft');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (469, 1, 463, 'Gearbox', 'gearbox');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (470, 1, 409, 'Driving system', 'driving-system');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (471, 1, 470, 'Wheel Rim', 'wheel-rim');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (472, 1, 470, 'Wheel Hub Unit', 'wheel-hub-unit');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (473, 1, 409, 'Brake System', 'brake-system');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (474, 1, 473, 'Brake Pads', 'brake-pads');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (475, 1, 473, 'Brake Master/Slave Pump', 'brake-master-slave-pump');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (476, 1, 473, 'Brake caliper', 'brake-caliper');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (477, 1, 473, 'Brake assembly', 'brake-assembly');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (478, 1, 409, 'Steering System', 'steering-system');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (479, 1, 478, 'Steering Gear', 'steering-gear');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (480, 1, 478, 'Steering Pump', 'steering-pump');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (481, 1, 478, 'Steering knuckle', 'steering-knuckle');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (482, 1, 478, 'Tie Rod End', 'tie-rod-end');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (483, 1, 409, 'Suspension System', 'suspension-system');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (484, 1, 409, 'Electrical Parts', 'Electrical%20Parts');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (485, 1, 484, 'Switches', 'switches');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (486, 1, 484, 'Suspension Bushing And Rubber Parts', 'suspension-bushing-and-rubber-parts');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (487, 1, 484, 'Cable', 'cable');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (488, 1, 484, 'Rubbers', 'rubbers');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (489, 1, 409, 'Body parts', 'body-parts');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (490, 1, 489, 'Auto Lamps', 'auto-lamps');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (491, 1, 489, 'Mirror', 'mirror');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (492, 1, 489, 'Handle', 'handle');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (493, 1, 489, 'Stamping Parts', 'stamping-parts');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (494, 1, 489, 'Bumper', 'bumper');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (495, 1, 489, 'Grille', 'grille');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (496, 1, 489, 'Anti-collision beam', 'anti-collision-beam');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (497, 1, 489, 'Subframe & axle', 'subframe-amp-axle');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (498, 1, 489, 'Part Number', 'part-number32');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (499, 1, NULL, 'New Products', 'new-products');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (500, 1, 499, 'Truck radiator', 'truck-radiator');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (501, 1, 499, 'OTHER', 'other');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (502, 1, NULL, 'Equipment & Parts for EV', 'equipment-parts-for-ev');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (503, 1, NULL, 'Industrial Machinery Parts', 'industrial-machinery-parts');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (504, 1, NULL, 'Modified Parts & Accessories', 'modified-parts-accessories');
INSERT INTO categories (id, site_id, parent_id, name, slug) VALUES (505, 1, NULL, 'Supply Chain Equipment', 'supply-chain-equipment');

-- Insert Products
INSERT INTO products (id, site_id, category_id, name, slug, image_url) VALUES (1, 1, 1, 'Hub unit 2DACF028GX for CHEVROLET', '63516', '../data/watermark/main/20260409/69d7691c7ecd8.jpg');
INSERT INTO products (id, site_id, category_id, name, slug, image_url) VALUES (2, 1, 1, 'Hub unit 43402-64B01 for CHEVROLET', '63515', '../data/watermark/main/20260409/69d7696306fdb.jpg');
INSERT INTO products (id, site_id, category_id, name, slug, image_url) VALUES (3, 1, 1, 'Ignition coil 3705010-NE01 for CHANGAN CS55PLUS', '63514', '../data/watermark/main/20260409/69d769bee326f.jpg');
INSERT INTO products (id, site_id, category_id, name, slug, image_url) VALUES (4, 1, 1, 'Ignition coil 4G22D4-3707000 for JINBEI', '63513', '../data/watermark/main/20260409/69d76a2a81de4.jpg');
INSERT INTO products (id, site_id, category_id, name, slug, image_url) VALUES (5, 1, 1, 'Front headlight - left 10035782 for MG MG 5', '63512', '../data/watermark/main/20260409/69d76a6887fbb.jpg');
INSERT INTO products (id, site_id, category_id, name, slug, image_url) VALUES (6, 1, 1, 'Tail light 11718577 for MG', '63511', '../data/watermark/main/20260409/69d76a8ad92ae.jpg');
INSERT INTO products (id, site_id, category_id, name, slug, image_url) VALUES (7, 1, 1, 'Left side light 3726010-CL01 for VICTORY EFFA', '63510', '../data/watermark/main/20260409/69d76ab501db6.jpg');
INSERT INTO products (id, site_id, category_id, name, slug, image_url) VALUES (8, 1, 1, 'Combined rear light assy S203F280503-0600-AB for CHANGAN', '63509', '../data/watermark/main/20260409/69d76ae3b29ae.jpg');
INSERT INTO products (id, site_id, category_id, name, slug, image_url) VALUES (9, 1, 1, 'Right front headlight assy 8111002W80 for TOYOTA', '63508', '../data/watermark/main/20260409/69d76b0a20928.jpg');
INSERT INTO products (id, site_id, category_id, name, slug, image_url) VALUES (10, 1, 1, 'Right rear side combined light 10D 945 096 for VW ID3', '63507', '../data/img_bucket/10D_945_096.jpg');
INSERT INTO products (id, site_id, category_id, name, slug, image_url) VALUES (11, 1, 1, 'Left rear side combined light 10D 945 095 for VW ID3', '63506', '../data/img_bucket/10D_945_095.jpg');
INSERT INTO products (id, site_id, category_id, name, slug, image_url) VALUES (12, 1, 1, 'Left front combined light assy 10D 941 029 for VW ID3', '63505', '../data/img_bucket/10D_941_029.jpg');
